# Generated by Django 3.1.3 on 2021-10-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayname', models.CharField(max_length=100)),
                ('dayweatherlogo', models.URLField(max_length=2000)),
                ('rainamount', models.CharField(max_length=100)),
                ('dayweathertext', models.CharField(max_length=100)),
                ('daytemp', models.CharField(max_length=100)),
            ],
        ),
    ]
