# Generated by Django 3.1.3 on 2021-10-24 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mvua', '0004_auto_20211023_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='dayname',
        ),
        migrations.AddField(
            model_name='home',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
