# Generated by Django 3.1.3 on 2021-10-24 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mvua', '0005_auto_20211024_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='dayhumidity',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
